version: "3.9"

# ======================================================
# 🧠 AI Job Screening System - Production Configuration
# ======================================================

services:
  # Redis Queue
  redis:
    image: redis:7-alpine
    container_name: redis_prod
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app_network
    ports:
      - "6379:6379"

  # Application Server (Express + API)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aijobscanner:v1.0
    container_name: app_server
    command: npm start
    env_file: .env
    environment:
      NODE_ENV: production
      REDIS_URL: ${REDIS_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      ZILLIZ_BASE_URL: ${ZILLIZ_BASE_URL}
      ZILLIZ_API_KEY: ${ZILLIZ_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
    depends_on:
      - redis
    ports:
      - "4000:4000"
    restart: always
    networks:
      - app_network

  # Background Worker (BullMQ)
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: aijobscanner:v1.0
    container_name: app_worker
    command: npm run start:worker
    env_file: .env
    environment:
      NODE_ENV: production
      REDIS_URL: ${REDIS_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      ZILLIZ_BASE_URL: ${ZILLIZ_BASE_URL}
      ZILLIZ_API_KEY: ${ZILLIZ_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
    depends_on:
      - redis
    restart: always
    networks:
      - app_network

# ======================================================
# Named Volumes & Networks
# ======================================================
volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
