# fly.toml app configuration file generated for ai-job-application-screening on 2025-10-11T10:26:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-job-application-screening'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
